In [4]:
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt
import rpy2.robjects as robj
import pyreadr
from easydict import EasyDict as edict
from tqdm import tqdm_notebook as tqdm
import sys
import time as Time
import pickle
from scipy.io import loadmat
from scipy.signal import decimate, detrend
%matplotlib inline

In [5]:
sys.path.append("/home/huaqingj/MyResearch/dynamicR2py")
from utils import *

In [26]:
MEG = loadmat("./data/subj1.mat")["DK_timecourse"]

In [27]:
kappa = 2.65
r = 6
Lmin = 60
downrate = 4
rate = 6
MaxM = 20

In [28]:
MEG = detrend(MEG)
MEG = decimate(MEG, q=10)

In [30]:
d, n = MEG.shape
time = np.linspace(0, 60, n)

In [31]:
t0 = Time()
dXmat, Xmat = GetBsplienEst(MEG, time)
Amat = GetAmat(dXmat, Xmat, time, 4)
midRes = GetNewEst(dXmat, Xmat, Amat, r=r, is_full=True)
ndXmat, nXmat = midRes.ndXmat, midRes.nXmat
finalRes = EGenDy(ndXmat, nXmat, kappa=kappa, Lmin=Lmin, MaxM=20, diag=True)
tc = Time()


Main Loop:   3%|▎         | 123/3600 [03:09<1:26:45,  1.50s/it]


Main Loop:   7%|▋         | 245/3600 [06:06<1:19:26,  1.42s/it]


Main Loop:  10%|█         | 367/3600 [08:55<1:12:34,  1.35s/it]


Main Loop:  14%|█▎        | 489/3600 [11:35<1:06:19,  1.28s/it]


Main Loop:  17%|█▋        | 611/3600 [14:06<1:00:29,  1.21s/it]


Main Loop:  20%|██        | 736/3600 [16:31<53:54,  1.13s/it]


Main Loop:  24%|██▍       | 862/3600 [18:49<48:14,  1.06s/it]


Main Loop:  27%|██▋       | 988/3600 [20:58<42:49,  1.02it/s]


Main Loop:  31%|███       | 1112/3600 [22:57<38:30,  1.08it/s]


Main Loop:  34%|███▍      | 1236/3600 [24:48<34:14,  1.15it/s]


Main Loop:  38%|███▊      | 1360/3600 [26:31<30:12,  1.24it/s]


Main Loop:  41%|████      | 1484/3600 [28:07<26:15,  1.34it/s]


Main Loop:  45%|████▍     | 1608/3600 [29:35<22:47,  1.46it/s]


Main Loop:  48%|████▊     | 1732/3600 [30:56<19:16,  1.62it/s]


Main Loop:  52%|█████▏    | 1856/3600 [32:10<16:28,  1.76it/s]


Main Loop:  55%|█████▌    | 1980/3600 [33:17<13:56,  1.94it/s]


Main Loop:  58%|█████▊    | 2104/3600 [34:17<11:30,  2.17it/s]


Main Loop:  62%|██████▏   | 2228/3600 [35:12<09:29,  2.41it/s]


Main Loop:  65%|██████▌   | 2352/3600 [36:00<07:41,  2.70it/s]


Main Loop:  69%|██████▉   | 2476/3600 [36:43<06:03,  3.09it/s]


Main Loop:  72%|███████▏  | 2600/3600 [37:20<04:37,  3.60it/s]


Main Loop:  76%|███████▌  | 2724/3600 [37:52<03:26,  4.23it/s]


Main Loop:  79%|███████▉  | 2848/3600 [38:19<02:28,  5.05it/s]


Main Loop:  83%|████████▎ | 2972/3600 [38:40<01:40,  6.24it/s]


Main Loop:  86%|████████▌ | 3096/3600 [38:58<01:01,  8.21it/s]


Main Loop:  91%|█████████ | 3267/3600 [39:14<00:24, 13.59it/s]


Main Loop: 100%|██████████| 3600/3600 [39:24<00:00,  1.52it/s] 

In [32]:
finalRes.mbic_ecpts

array([], dtype=float64)

In [33]:
finalRes.chgMat

array([[2725.,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf],
       [2591., 3130.,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf],
       [ 201., 2591., 3130.,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf],
       [ 201., 2329., 2622., 2831.,   inf,   inf,   inf,   inf,   inf,
          inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf],
       [ 203.,  405., 2329., 2622., 2831.,   inf,   inf,   inf,   inf,
          inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf],
       [ 202.,  406., 1944., 2332., 2622., 2831.,   inf,   inf,   inf,
          inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,   inf,
          inf,   inf],
       [ 2

In [35]:
finalRes.U - finalRes.U0

array([ 3156.45326363,  6312.90652726,  9469.35979089, 12625.81305453,
       15782.26631816, 18938.71958179, 22095.17284542, 25251.62610905,
       28408.07937268, 31564.53263632, 34720.98589995, 37877.43916358,
       41033.89242721, 44190.34569084, 47346.79895447, 50503.25221811,
       53659.70548174, 56816.15874537, 59972.612009  , 63129.06527263,
       66285.51853626])

In [36]:
2*r*np.log(n)**kappa* (np.arange(1, 20+2))

array([ 3156.45326363,  6312.90652726,  9469.35979089, 12625.81305453,
       15782.26631816, 18938.71958179, 22095.17284542, 25251.62610905,
       28408.07937268, 31564.53263632, 34720.98589995, 37877.43916358,
       41033.89242721, 44190.34569084, 47346.79895447, 50503.25221811,
       53659.70548174, 56816.15874537, 59972.612009  , 63129.06527263,
       66285.51853626])